
FLOW_SWITCH:
  WEB_SCRAPPING: False
  DATA_PREPROCESSING: True
  

SCRAPING_VARS:
  CONTROL:
    COLLEGE_SCRAPPING: True
    NBA_SCRAPING: True
  COLLEGE:
    START_YEAR: 1987
    END_YEAR: 2022
    CONFERENCES_PER_SEASON_EXCEL: 'conferences_per_season_url_{start_year}_{end_year}.xlsx'
    COLLEGES_PER_SEASON_EXCEL: 'colleges_per_season_url_{start_year}_{end_year}.xlsx'
    PLAYERS_URLS_EXCEL: 'college_players_url_{start_year}_{end_year}.xlsx'
    PLAYERS_RAW_DATA_EXCEL: 'college_players_data_raw_{start_year}_{end_year}.xlsx'
    COLLEGE_REFERENCE_BASE_URL: 'https://www.sports-reference.com'
    TABLES_IDS:
      PER_GAME: 'players_per_game'
      TOTALS: 'players_totals'
      PER_MINUTE: 'players_per_min'
      PER_POSS: 'players_per_poss'
      ADVANCED: 'players_advanced'
  NBA:
    START_YEAR: 1987
    END_YEAR: 2022
    BASKERBALL_REFERENCE_BASE_URL: 'https://www.basketball-reference.com'
    NBA_LEAGUE_PER_GAME_STATS: '/leagues/NBA_{year}_per_game.html'
    NBA_LEAGUE_PER_100POSS_STATS: '/leagues/NBA_{year}_per_poss.html'
    NBA_LEAGUE_ADVANCED_STATS: '/leagues/NBA_{year}_advanced.html'
    PER_GAME_TABLE_ID: 'per_game_stats'
    PER_POSS_TABLE_ID: 'per_poss_stats'
    ADVANCED_TABLE_ID: 'advanded_stats'
    PLAYERS_URLS_EXCEL: 'nba_players_url_{start_year}_{end_year}.xlsx'
    PLAYERS_RAW_DATA_EXCEL: 'nba_players_data_raw_{start_year}_{end_year}.xlsx'
    TABLES_IDS:
      PER_GAME: 'per_game'
      TOTALS: 'totals'
      PER_MINUTE: 'per_minute'
      PER_POSS: 'per_poss'
      ADVANCED: 'advanced'

DATA_PREPROCESS_PIPELINE:
  CONTROL:
    FEATURESET_BUILD: False
    FEATURESET_IMPUTATION: True
    FEATURESET_CORRELATION: True
  FEATURE_SET:
    YEAR_BUILD: 1996
    FEATURESET_EXCEL: 'featureset_{output}_{build_year}.xlsx'
    FEATURESET_EXCEL_PREPROCESSED: 'featureset_{output}_preprocessed_{build_year}.xlsx'
    NBA:
      NBA_SUCCESS_VAR: 'ws'
      SUCCESS_AGG: 'sum'
      ROOKIE_CONTRACT: 4
      TABLE_TYPES:
        PER_GAME: 'PER_GAME_DATA'
        TOTALS: 'SEASON_TOTAL_DATA'
        PER_MINUTE: 'PER_36_MIN_DATA'
        PER_POSS: 'PER_100_POSS_DATA'
        ADVANCED: 'SEASON_ADVANCED_DATA'
        
    COLLEGE:
      TABLE_TYPES:
        PER_GAME: 'PER_GAME_DATA'
        TOTALS: 'SEASON_TOTAL_DATA'
        PER_MINUTE: 'PER_40_MIN_DATA'
        PER_POSS: 'PER_100_POSS_DATA'
        ADVANCED: 'SEASON_ADVANCED_DATA'

      TABLES_LOAD: [
        'PER_GAME_DATA',
        #'SEASON_TOTAL_DATA',
        #'PER_40_MIN_DATA',
        #'PER_100_POSS_DATA',
        'SEASON_ADVANCED_DATA',
      ]

      MERGING_COLUMNS: [
        'id', 'name', 'season', 'school', 'draft_overall', 'draft_year', 'draft'
        ]

      NORMALIZED_FEATURES: [
        'pts (game)',
        'ast (game)',
        'tbr (game)',
        'ws (advanced)'
      ]

      OUTLIER_DETECTOR_VARS: [
        ['3p% (game)', '3pa (game)', 0.5]
      ]

      NULL_COLUMNS_DROP: 0.5

      NORM_VAR: 'strength_of_schedule (game)'

      SPEC_DATA:
        PER_GAME_DATA: [
          'n_seasons',
          'pts (dev)',
          'pts (prop)',
          'tbr (prop)',
          'ast (prop)',
          'stl (prop)',
          'tov (prop)'
        ]

        SEASON_TOTAL_DATA: [

        ]

        PER_40_MIN_DATA: [

        ]

        PER_100_POSS_DATA: [

        ]

        SEASON_ADVANCED_DATA: [
          'ts% (dev)',
          'efg% (dev)',
          'ws (prop)',
        ]

  CORRELATION:
    MAX_VARS_PLOT: 9
    PLOT_TYPE_1_TITLE: 'Correlation College to NBA (Success As {var})'
    PLOT_TYPE_3_TITLE: 'High Correlation Var - {corr} - {x} vs {y}'
    PLOT_TYPE_1_FILE: 'ALL_Correlation_to_{var}_{number}.png'
    PLOT_TYPE_2_FILE: 'Correlation_to_{var}_{number}.png'
    PLOT_TYPE_3_FILE: 'high_correlation_{x}_{y}.png'
    HIGH_CORR_THRESHOLD: 0.15
    FOLDER:
      SUCCESS_VAR: '{var}'
    NOT_RELEVANT_COLUMNS: [
      'id',
      'draft_overall',
      'draft_year',
      'draft',
      'season',
      'position'
    ]

    

FOLDERS:
  DATA: 'data'
  URL: 'url'
  COLLEGE_RAW: 'college_players_raw_data'
  NBA_RAW: 'nba_players_raw_data'
  FEATURESET: 'featureset'
  CORRELATION: 'correlation_plots'
  


